 -- Use all of the functions below, find out what they do, write a description
 -- for them here or in the comments of the code. Add a meaningful column alias

CONCAT(COLUMN1, COLUMN2) AS ALIAS_NAME
 LOWER(COLUMN)
 UPPER(COLUMN)
 TRIM(COLUMN)
 LENGTH(COLUMN)
 SUBSTRING(COLUMN, START, LENGTH)
 ROUND(COLUMN, DECIMAL_PLACES)
 DATE_ADD(COLUMN, INTERVAL EXPRESSION UNIT)
 DATE_SUB(COLUMN, INTERVAL EXPRESSION UNIT)

 FORMAT(COLUMN, FORMAT_STRING)SELECT CONCAT(TIME_MEAL_ORDERED, MEAL_NAME) AS ALIAS_NAME FROM MEAL_ORDER_WITH_DETAILS.
#CONCATENA DUE COLONNE OVVERO LE UNISCE
SELECT UPPER(MEAL_NAME) AS UPPERCASE_NAME, #TI RIPORTA IN COLONNA DOVE TUTTI I NOMI SONO IN MAIUSCOLO
       LOWER(MEAL_NAME) AS LOWERCASE_NAME, #TI RIPORTA IN COLONNA TUTTI I NOMI IN MINUSCOLO
       TRIM(MEAL_NAME) AS TRIM_NAME,       #UTILIZZATO PER ELIMINARE GLI SPAZI VUOTI
       LENGTH(MEAL_NAME) AS LEGTH_NAME,     #LUNGHEZZA DELLA STRINGA
       SUBSTRING(MEAL_NAME,  LENGTH(MEAL_NAME)) AS SUBSTRING_NAME, #UTILIZZATO PER FAR PARTIRE LA STRINGA DA UNA SPECIFICO INIZIO
       ROUND(MEAL_NAME, PRICE) AS ROUND_NAME,  #ARROTONDA I NUMERI DECIMANLI
       DATE_ADD(TIME_MEAL_ORDERED, INTERVAL 1 WEEK) AS DATEADD_NAME, #VA A MODIFICARE IL TEMPO DELL' ORDINE AGGIUNGENDO UN INTERVALLO TEMPORALE
       DATE_SUB(TIME_MEAL_ORDERED, INTERVAL 5 HOUR) AS DATESUB_NAME, #VA A MODIFICARE IL TEMPO DELL'ORDINE SOTTRAENDO UN INTERVALLO TEMPORALE
       FORMAT(TIME_MEAL_ORDERED, '')AS FORMAT_NAME, #TI RESTITUISCE SOTTO FORMA DI STRINGA

 -- Using DATE_ADD or DATE_SUB and the following SQL
 -- SELECT NOW();
 -- Select your birthday by passing the result into the next item
 -- i.e. DATE_ADD(DATE_ADD(NOW(), INTERVAL 7 DAY), INTERVAL 2 MONTH) as BIRTHDAY_DATE
       DATE_ADD(DATE_ADD(TIME_MEAL_ORDERED, INTERVAL 42382 SECOND), INTERVAL 255 DAY) as BIRTHDAY_DATE
FROM MEAL_ORDER_WITH_DETAILS