CREATE TABLE MEAL (
  NAME VARCHAR(255),
  PRICE DOUBLE,
  CALORIES INT
);

CREATE TABLE INGREDIENT(
  NAME VARCHAR(255),
  COINTAIN_LACTOSE BOOLEAN,
  VEGETERIAN BOOLEAN,
  VEGAN BOOLEAN,
  GLUTEN_FREE BOOLEAN
  );

  INSERT INTO INGREDIENT(NAME, COINTAIN_LACTOSE, VEGETERIAN, VEGAN, GLUTEN_FREE)
  VALUES('Eggs',false,true,false,true);
  INSERT INTO INGREDIENT(NAME, COINTAIN_LACTOSE, VEGETERIAN, VEGAN, GLUTEN_FREE)
  VALUES('Bread',true,true,true,false);
  INSERT INTO INGREDIENT(NAME, COINTAIN_LACTOSE, VEGETERIAN, VEGAN, GLUTEN_FREE)
  VALUES('Beef Patty',false,false,false,true);
  INSERT INTO INGREDIENT(NAME, COINTAIN_LACTOSE, VEGETERIAN, VEGAN, GLUTEN_FREE)
  VALUES('Lettuce',false,true,true,true);
  INSERT INTO INGREDIENT(NAME, COINTAIN_LACTOSE, VEGETERIAN, VEGAN, GLUTEN_FREE)
  VALUES('Yoghurt',true,true,false,true);