create table STUDENT(
ID_STUDENT INT auto_increment,
NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
GRADE INT,
primary key (ID_STUDENT)
);

insert into STUDENT(NAME,LAST_NAME, GRADE)
VALUES('Ciccio','Graziani',59),
	  ('Sabrina','Ferilli',70),
	  ('Marco','Adriani',15),
	  ('Rocco','Toscano',99);

select * from STUDENT;

create table COURSE(
ID_STUDENT INT auto_increment,
COURSE_NAME VARCHAR(255),
PROFESSOR VARCHAR(255),
CLASSROOM CHAR(50),
primary key (ID_STUDENT)
);

insert into COURSE(COURSE_NAME, PROFESSOR, CLASSROOM)
VALUES('Fisica quantistica','Prof. Leonard Aufstade','a'),
      ('Chimica','Prof Wallawitz','b'),
      ('Teoria delle Stringhe','Prof Sheldon Cooper','c');

--INNER JOIN

SELECT S.NAME
FROM STUDENT S INNER JOIN COURSE C
ON S.ID_STUDENT = C.ID_STUDENT
GROUP BY C.COURSE_NAME;

--LEFT JOIN

SELECT S.NAME
FROM STUDENT S LEFT JOIN COURSE C
ON S.ID_STUDENT = C.ID_STUDENT
GROUP BY C.COURSE_NAME;

--LEFT JOIN WITHOUT COMMON KEY

SELECT S.NAME
FROM STUDENT S LEFT JOIN COURSE C
ON S.ID_STUDENT = C.ID_STUDENT
WHERE S.ID_STUDENT IS NULL;

--RIGHT JOIN

SELECT S.NAME
FROM STUDENT S RIGHT JOIN COURSE C
ON S.ID_STUDENT = C.ID_STUDENT
GROUP BY C.COURSE_NAME;

--RIGHT JOIN WITHOUT COMMON KEY

SELECT S.NAME
FROM STUDENT S LEFT JOIN COURSE C
ON S.ID_STUDENT = C.ID_STUDENT
WHERE S.ID_STUDENT IS NULL;

--FULL OUTER JOIN

SELECT * FROM STUDENT S
LEFT JOIN COURSE C ON C.ID_STUDENT = S.ID_STUDENT
UNION
SELECT * FROM STUDENT S
RIGHT JOIN COURSE C ON C.ID_STUDENT = S.ID_STUDENT;

--FULL OUTER JOIN WITH COMMON KEY

SELECT * FROM STUDENT S
LEFT JOIN COURSE C ON C.ID_STUDENT = S.ID_STUDENT
WHERE C.ID_STUDENT IS NULL
UNION
SELECT * FROM STUDENT S
RIGHT JOIN COURSE C ON C.ID_STUDENT = S.ID_STUDENT;
WHERE I.ID_STUDENT IS NULL