CREATE TABLE MEAL (
  NAME VARCHAR(255),
  PRICE DOUBLE,
  CALORIES INT
);

INSERT INTO MEAL(NAME, PRICE, CALORIES)
VALUES ('Spaghetti Bolognese', 12.99, 600),
       ('Grilled Chicken Sandwich', 8.99, 400),
       ('Pesto Pasta', 10.99, 550),
       ('Steak and Mash', 19.99, 800),
       ('Sushi Platter', 15.99, 700);

CREATE TABLE INGREDIENT(
  NAME VARCHAR(255),
  COINTAIN_LACTOSE BOOLEAN,
  VEGETARIAN BOOLEAN,
  VEGAN BOOLEAN,
  GLUTEN_FREE BOOLEAN
  );

  INSERT INTO INGREDIENT(NAME, COINTAIN_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE)
  VALUES('Eggs',false,true,false,true);
  INSERT INTO INGREDIENT(NAME, COINTAIN_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE)
  VALUES('Bread',true,true,true,false);
  INSERT INTO INGREDIENT(NAME, COINTAIN_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE)
  VALUES('Beef Patty',false,false,false,true);
  INSERT INTO INGREDIENT(NAME, COINTAIN_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE)
  VALUES('Lettuce',false,true,true,true);
  INSERT INTO INGREDIENT(NAME, COINTAIN_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE)
  VALUES('Yoghurt',true,true,false,true);

